openapi: 3.0.3
info:
  title: Customer Service API - OpenAPI 3.0
  description: |-
    Сервисная служба по ремонту и техническому обслуживанию клиентов.
    
    Описание сущности `SupportService` - запрос в техническую поддержку сервиса. 

    _Данная сущность отвечает за запросы клиентов в техническую поддержку сервиса. В ней реализована логика получения списка запросов от клиентов, получения конкретного запроса, удаление запроса после того как заказ будет выполнен, изменение статуса запроса._
  
  # termsOfService: http://swagger.io/terms/
  # contact:
  #   email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
servers:
  - url: http://localhost:8876/api/
tags:
  - name: SupportService
    description: Запросы в техническую поддержку сервиса
    # externalDocs:
    #   description: Find out more
    #   url: http://swagger.io
  # - name: store
  #   description: Access to Petstore orders
  #   externalDocs:
  #     description: Find out more about our store
  #     url: http://swagger.io
  # - name: user
  #   description: Operations about user
paths:
  /order/support:
    get:
      tags:
        - SupportService
      summary: Получаем список запросов в тех.поддержку
      description: Получаем список запросов в тех.поддержку
      operationId: support_orders
      # requestBody:
      #   description: Получаем список запросов в тех.поддержку
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/SupportService'
          
      #   required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportServicePost'
        '400':
          description:   
                Invalid tag value
    put:
      tags:
        - SupportService
      summary: Обновление статуса заказа
      description: Обновление статуса заказа по объекту json
      operationId: support_order_update
      requestBody:
        description: Обновление статуса заказа по объекту json
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupportService'
          
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportService'
        '404':
          description: Not successfuly operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportService'
    post:
      tags:
        - SupportService
      summary: Добавление запроса в тех.поддержку сервиса
      description: Добавить новый запрос в тех.поддержку от клиента  
      operationId: support_order_create
      requestBody:
        description: Добавить новый запрос в тех.поддержку от клиента 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupportService'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportServicePost'
        '405':
          description: Invalid input
            
  /order/support/{id}:
    get:
      tags:
        - SupportService
      summary: Получаем запрос в тех.поддержку
      description: Получаем запрос в тех.поддержку по id
      operationId: support_order
      parameters:
        - name: id
          in: path
          description: ID of order to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupportService'
        '400':
          description: Invalid status value
    delete:
      tags:
        - SupportService
      summary: Получаем запрос в тех.поддержку
      description: Получаем запрос в тех.поддержку по id
      operationId: support_order
      parameters:
        - name: id
          in: path
          description: ID of order to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupportService'
        '400':
          description: Invalid status value
components:
  schemas:
    SupportService:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 5
        name:
          type: string
          example: Заявка 51
        content:
          type: string
          example: Кофемашина не работает
        customerId:
          type: integer
          format: int64
          example: 9
        deviceId:
          type: integer
          format: int64
          example: 92
        date_creation:
          type: integer
          example: 1670270749
        status:
          type: string
          example: completed
    SupportServicePost:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 5
          name:
            type: string
            example: Заявка 51
          content:
            type: string
            example: Кофемашина не работает
          customerId:
            type: integer
            format: int64
            example: 9
          deviceId:
            type: integer
            format: int64
            example: 92
          date_creation:
            type: integer
            example: 1670270749
          status:
            type: string
            example: completed
  requestBodies:
    SupportService:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SupportService'
